/// <reference types="@sveltejs/kit" />
/// <reference no-default-lib="true"/>
/// <reference lib="esnext" />
/// <reference lib="webworker" />

import { build, files, version } from '$service-worker';

declare const self: ServiceWorkerGlobalScope;

// ── Cache names ───────────────────────────────────────────────────────────────
// Version-stamped so a new build always gets a fresh cache.
const SHELL_CACHE  = `shell-${version}`;
const STATIC_CACHE = `static-${version}`;

// ── Assets to pre-cache ───────────────────────────────────────────────────────
// build  = JS/CSS chunks generated by Vite
// files  = everything in ui/static/ (icons, manifest, favicon)
const SHELL_ASSETS  = build;        // versioned — change every deploy
const STATIC_ASSETS = files;        // infrequently-changed (icons, manifest)

// ── Install: pre-cache the app shell ─────────────────────────────────────────
self.addEventListener('install', (event) => {
	event.waitUntil(
		Promise.all([
			caches.open(SHELL_CACHE).then((c) => c.addAll(SHELL_ASSETS)),
			caches.open(STATIC_CACHE).then((c) => c.addAll(STATIC_ASSETS)),
		]).then(() => {
			// Skip waiting so the new SW activates immediately
			self.skipWaiting();
		})
	);
});

// ── Activate: clean up old versioned caches ───────────────────────────────────
self.addEventListener('activate', (event) => {
	event.waitUntil(
		caches.keys().then((keys) =>
			Promise.all(
				keys
					.filter((k) => k !== SHELL_CACHE && k !== STATIC_CACHE)
					.map((k) => caches.delete(k))
			)
		).then(() => {
			// Take control of all clients immediately
			self.clients.claim();
		})
	);
});

// ── Fetch: routing strategy ────────────────────────────────────────────────────
self.addEventListener('fetch', (event) => {
	const { request } = event;
	const url = new URL(request.url);

	// 1. Never intercept PocketBase API calls — always network
	//    Includes /api/, /_/, /pb_ paths
	if (
		url.pathname.startsWith('/api/') ||
		url.pathname.startsWith('/_/') ||
		url.pathname.startsWith('/pb_')
	) {
		return; // fall through to browser default (network)
	}

	// 2. Only handle same-origin requests
	if (url.origin !== self.location.origin) return;

	// 3. Only handle GET requests
	if (request.method !== 'GET') return;

	event.respondWith(handleFetch(request, url));
});

async function handleFetch(request: Request, url: URL): Promise<Response> {
	// ── Static assets (versioned build artifacts): cache first ─────────────────
	// These have content hashes in their filenames — safe to serve from cache.
	if (SHELL_ASSETS.includes(url.pathname) || STATIC_ASSETS.includes(url.pathname)) {
		const cached = await caches.match(request);
		if (cached) return cached;

		// Not in cache yet — fetch and store
		try {
			const response = await fetch(request);
			if (response.ok) {
				const cache = await caches.open(SHELL_CACHE);
				cache.put(request, response.clone());
			}
			return response;
		} catch {
			return new Response('Offline', { status: 503 });
		}
	}

	// ── Navigation requests (HTML pages): network first, cached shell fallback ──
	// Tries the network; if offline serves the cached app shell so the SPA
	// can still render (PocketBase data will fail gracefully with toasts).
	if (request.mode === 'navigate' || request.headers.get('accept')?.includes('text/html')) {
		try {
			const response = await fetch(request);
			if (response.ok) {
				// Cache the latest version of this page
				const cache = await caches.open(SHELL_CACHE);
				cache.put(request, response.clone());
			}
			return response;
		} catch {
			// Offline fallback: serve cached root page so the SPA boots
			const fallback =
				(await caches.match(request)) ||
				(await caches.match('/')) ||
				new Response('Offline — abre la app cuando tengas conexión.', {
					status: 503,
					headers: { 'Content-Type': 'text/plain; charset=utf-8' },
				});
			return fallback;
		}
	}

	// ── Everything else: network first ───────────────────────────────────────────
	try {
		return await fetch(request);
	} catch {
		const cached = await caches.match(request);
		return cached ?? new Response('Offline', { status: 503 });
	}
}
